In [1]:
from numpy import random

In [2]:
x=random.randint(100, size=(5))
x

array([29,  2, 92, 48,  2])

In [3]:
x=random.randint(100, size=(3,5))
x

array([[64, 66, 36,  1, 79],
       [95, 17, 49, 57, 79],
       [11, 25, 91,  3, 87]])

In [4]:
x=random.choice([3,5,7,9])
x

9

In [5]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
a= np.array_split(arr,2)
print(a)

[array([1, 2, 3]), array([4, 5, 6])]


In [9]:
arr= np.array([1,2,3,4,5,6])
a= np.array_split(arr,2)
print(a[0])

[1 2 3]


In [10]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[3 7 5 7 7 3 7 7 7 7 7 3 7 5 7 7 7 5 7 5 7 5 3 7 7 5 7 7 7 7 5 7 5 7 5 5 7
 7 7 7 3 5 5 7 7 5 5 3 7 7 7 7 7 7 5 7 5 7 7 5 7 7 3 7 5 5 7 5 5 7 5 7 7 5
 7 5 7 7 7 5 7 3 3 3 7 5 5 3 7 7 5 5 7 5 5 7 3 7 3 7]


In [15]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[3 4 2 1 5]


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))
print(arr)

[4 1 3 2 5]
[1 2 3 4 5]
