In [35]:
import numpy as np

In [36]:
arr=np.random.randint(20,100,20)

In [37]:
print(type(arr), arr.size, arr.shape, arr.dtype, arr.itemsize)

<class 'numpy.ndarray'> 20 (20,) int32 4


In [38]:
print(arr)

[90 26 51 97 67 41 34 67 85 81 74 80 81 90 85 41 82 88 21 84]


In [39]:
arr[0]

90

In [40]:
arr[5]

41

In [41]:
arr[:5]

array([90, 26, 51, 97, 67])

In [42]:
arr[-5:]

array([41, 82, 88, 21, 84])

In [43]:
arr[::2]

array([90, 51, 67, 34, 85, 74, 81, 85, 82, 21])

In [44]:
arr[0]=100
arr

array([100,  26,  51,  97,  67,  41,  34,  67,  85,  81,  74,  80,  81,
        90,  85,  41,  82,  88,  21,  84])

In [45]:
arr[-5:]=arr[:5]
arr

array([100,  26,  51,  97,  67,  41,  34,  67,  85,  81,  74,  80,  81,
        90,  85, 100,  26,  51,  97,  67])

In [46]:
arr[[4,6,9,1]]

array([67, 34, 81, 26])

In [47]:
arr[[0,1,2,3]]=[4,5,6,7]

In [48]:
arr

array([  4,   5,   6,   7,  67,  41,  34,  67,  85,  81,  74,  80,  81,
        90,  85, 100,  26,  51,  97,  67])

In [49]:
arr[[0,1,2,3]]=arr[[4,5,6,7]]
arr

array([ 67,  41,  34,  67,  67,  41,  34,  67,  85,  81,  74,  80,  81,
        90,  85, 100,  26,  51,  97,  67])

In [50]:
arr>90

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False])