In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
#dimension of array
print(a.ndim) 

1


In [4]:
#dimension of array
b=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(b.ndim)

3


In [5]:
#dimension of array  b
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [6]:
#priting a random aaray
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
#reshape of array
w=np.arange(12).reshape(3,2,2)
w

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [8]:
#printing element of location
w[0][1][1]

3

In [9]:
w=np.arange(21).reshape(7,3,1)
w

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14]],

       [[15],
        [16],
        [17]],

       [[18],
        [19],
        [20]]])

In [11]:
w=np.arange(21).reshape(7,1,3)
w

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]],

       [[15, 16, 17]],

       [[18, 19, 20]]])

In [12]:
w=np.arange(32).reshape(4,2,2,2)
w

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])

In [14]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
#addition of two element in an array
a[2][1]+a[2][2]

19

In [16]:
#slicing
a=np.array([1,2,3,4,5])
a[0:3]

array([1, 2, 3])

In [17]:
a[-3:-1]

array([3, 4])

In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print("dim of a=",a.ndim)
print(b)
print("dim of b=",b.ndim)
print(c)
print("dim of c=",c.ndim)
print(d)
print("dim of d=",d.ndim)

42
dim of a= 0
[1 2 3 4 5]
dim of b= 1
[[1 2 3]
 [4 5 6]]
dim of c= 2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dim of d= 3


In [19]:
#copy aaray

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
#view function

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], ndmin=2)

print(arr)
print('shape of array :', arr.shape)

a=arr.reshape(2,6)
print(a)

b=arr.reshape(3,4)
print(b)

c=arr.reshape(4,3)
print(c)

d=arr.reshape(3,2,2)
print(d)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
shape of array : (1, 12)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(4,2).base)

[1 2 3 4 5 6 7 8]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
arr = np.array([1, 2, 3])

for id, x in np.ndenumerate(arr):
  print(id, x)

(0,) 1
(1,) 2
(2,) 3


In [26]:
#joining two array

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr.ndim

[1 2 3 4 5 6]


1

In [36]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) #axis=0

print(arr)

arr.ndim

[[1 2 5 6]
 [3 4 7 8]]


2

In [37]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1) #axis=0

print(arr)

arr.ndim

[[1 4]
 [2 5]
 [3 6]]


2

In [38]:
#horizontal 

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

arr.ndim

[1 2 3 4 5 6]


1

In [39]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

arr.ndim

[[[1 4]
  [2 5]
  [3 6]]]


3

In [41]:
#spilitting an array

arr = np.array([1, 2, 3, 4, 5, 6])

arr1 = np.array_split(arr, 2)

print(arr1)

arr2 = np.array_split(arr, 3)

print(arr2)

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
#finding location of any element 
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [43]:
#finding location of odd no.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [44]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [45]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [46]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [47]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [48]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [49]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

a = arr[x]

print(a)

[41 43]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr2 = arr[arr % 2 == 0]

print(arr2)

[2 4 6]


In [51]:
arr = np.array([41, 42, 43, 44])

arr1= arr[arr > 42]

print(arr1)

[43 44]
